---
title: "Pre Procesado de datos en R"
author: "jerf"
date: "13/6/2021"
output: html_document
---
```{r}
dataset = read.csv("Data.csv")
dataset
```


# Tratamiento de los valores NA

```{r}
dataset$Age = ifelse(is.na(dataset$Age), 
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)), 
                     dataset$Age)

dataset
```


```{r}
dataset$Salary = ifelse(is.na(dataset$Salary), 
                     ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)), 
                     dataset$Salary)

dataset
```


## Datos categ칩ricos

### Codificar las variables categ칩ricas
```{r}
dataset$Country = factor(dataset$Country, 
                         levels =c("France", "Spain", "Germany"),
                         labels= c(1,2,3))
dataset
```

```{r}
dataset$Purchased = factor(dataset$Purchased, 
                         levels =c("No", "Yes"),
                         labels= c(0,1))
dataset
```


## Dividir dataset en conjunto de entranmiento y conjunto de test

```{r}
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
split
```


El valor TRUE implica que esa observaci칩n ser치 para entrenar
```{r}
training_set = subset(dataset, split == TRUE)
training_set
testing_set = subset(dataset, split == FALSE)
testing_set
```



## Escalado de datos

Standardisation $$x_{stand}=\frac{x-mean(x)}{sd(x)}$$

```{r}
training_set[,2:3] = scale(training_set[,2:3])
training_set
testing_set[,2:3] = scale(testing_set[,2:3])
testing_set
```


Normalisation $$x_{norm} = \frac{x-min(x)}{max(x)-min(x)}$$
